#!/usr/bin/env perl
# Copyright [2018-2022] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


### Test Hum::GrcTpfs

use strict;
use warnings;

use Test::More qw( no_plan );
use Test::Requires qw( WrapDBI DBD::Oracle );

use Data::Dumper;

#Hum::Tracking::track_db_user('chromoview');

use_ok('Hum::GrcTpfs', qw(get_grc_tpf_names) );

my @expected = (
          [
            'Human',
            '1',
            'GRC__HUMAN__ALT_REF_LOCI_1__1'
          ],
          [
            'Human',
            '1',
            'GRC__HUMAN__ALT_REF_LOCI_2__1'
          ],
          [
            'Human',
            '1',
            'GRC__HUMAN__PLACEHOLDER__1'
          ],
          [
            'Human',
            '1',
            'UNPL_1'
          ],
          [
            'Human',
            '1',
            undef
          ],
          [
            'Human',
            '10',
            'GRC__HUMAN__ALT_REF_LOCI_1__10'
          ],
          [
            'Human',
            '10',
            'UNPL_10'
          ],
          [
            'Human',
            '10',
            undef
          ],
          [
            'Human',
            '11',
            'GRC__HUMAN__ALT_REF_LOCI_1__11'
          ],
          [
            'Human',
            '11',
            'GRC__HUMAN__ALT_REF_LOCI_2__11'
          ],
          [
            'Human',
            '11',
            'GRC__HUMAN__ALT_REF_LOCI_3__11'
          ],
          [
            'Human',
            '11',
            'GRC__HUMAN__PLACEHOLDER__11'
          ],
          [
            'Human',
            '11',
            'UNPL_11'
          ],
          [
            'Human',
            '11',
            undef
          ],
          [
            'Human',
            '12',
            'GRC__HUMAN__ALT_REF_LOCI_1__12'
          ],
          [
            'Human',
            '12',
            'GRC__HUMAN__ALT_REF_LOCI_2__12'
          ],
          [
            'Human',
            '12',
            undef
          ],
          [
            'Human',
            '13',
            'GRC__HUMAN__ALT_REF_LOCI_1__13'
          ],
          [
            'Human',
            '13',
            'UNPL_13'
          ],
          [
            'Human',
            '13',
            undef
          ],
          [
            'Human',
            '14',
            'GRC__HUMAN__ALT_REF_LOCI_1__14'
          ],
          [
            'Human',
            '14',
            'GRC__HUMAN__PLACEHOLDER__14'
          ],
          [
            'Human',
            '14',
            'UNPL_14'
          ],
          [
            'Human',
            '14',
            undef
          ],
          [
            'Human',
            '15',
            'GRC__HUMAN__ALT_REF_LOCI_1__15'
          ],
          [
            'Human',
            '15',
            'GRC__HUMAN__ALT_REF_LOCI_2__15'
          ],
          [
            'Human',
            '15',
            'GRC__HUMAN__PLACEHOLDER__15'
          ],
          [
            'Human',
            '15',
            'UNPL_15'
          ],
          [
            'Human',
            '15',
            undef
          ],
          [
            'Human',
            '16',
            'GRC__HUMAN__ALT_REF_LOCI_1__16'
          ],
          [
            'Human',
            '16',
            'GRC__HUMAN__PLACEHOLDER__16'
          ],
          [
            'Human',
            '16',
            'UNPL_16'
          ],
          [
            'Human',
            '16',
            undef
          ],
          [
            'Human',
            '17',
            'GRC__HUMAN__ALT_REF_LOCI_1__17'
          ],
          [
            'Human',
            '17',
            'GRC__HUMAN__ALT_REF_LOCI_2__17'
          ],
          [
            'Human',
            '17',
            'GRC__HUMAN__PLACEHOLDER__17'
          ],
          [
            'Human',
            '17',
            'UNPL_17'
          ],
          [
            'Human',
            '17',
            undef
          ],
          [
            'Human',
            '18',
            'GRC__HUMAN__ALT_REF_LOCI_1__18'
          ],
          [
            'Human',
            '18',
            'GRC__HUMAN__ALT_REF_LOCI_2__18'
          ],
          [
            'Human',
            '18',
            'GRC__HUMAN__PLACEHOLDER__18'
          ],
          [
            'Human',
            '18',
            'UNPL_18'
          ],
          [
            'Human',
            '18',
            undef
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_10__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_11__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_12__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_13__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_14__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_15__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_16__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_17__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_18__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_19__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_1__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_20__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_21__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_22__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_23__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_24__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_25__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_26__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_27__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_28__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_29__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_2__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_30__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_31__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_32__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_33__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_34__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_35__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_3__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_4__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_5__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_6__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_7__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_8__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__ALT_REF_LOCI_9__19'
          ],
          [
            'Human',
            '19',
            'GRC__HUMAN__PLACEHOLDER__19'
          ],
          [
            'Human',
            '19',
            'UNPL_19'
          ],
          [
            'Human',
            '19',
            undef
          ],
          [
            'Human',
            '2',
            'GRC__HUMAN__ALT_REF_LOCI_1__2'
          ],
          [
            'Human',
            '2',
            'GRC__HUMAN__ALT_REF_LOCI_2__2'
          ],
          [
            'Human',
            '2',
            'GRC__HUMAN__PLACEHOLDER__2'
          ],
          [
            'Human',
            '2',
            'UNPL_2'
          ],
          [
            'Human',
            '2',
            undef
          ],
          [
            'Human',
            '20',
            'GRC__HUMAN__ALT_REF_LOCI_1__20'
          ],
          [
            'Human',
            '20',
            'GRC__HUMAN__PLACEHOLDER__20'
          ],
          [
            'Human',
            '20',
            'UNPL_20'
          ],
          [
            'Human',
            '20',
            undef
          ],
          [
            'Human',
            '21',
            'GRC__HUMAN__ALT_REF_LOCI_1__21'
          ],
          [
            'Human',
            '21',
            'GRC__HUMAN__PLACEHOLDER__21'
          ],
          [
            'Human',
            '21',
            'UNPL_21'
          ],
          [
            'Human',
            '21',
            undef
          ],
          [
            'Human',
            '22',
            'GRC__HUMAN__ALT_REF_LOCI_1__22'
          ],
          [
            'Human',
            '22',
            'GRC__HUMAN__ALT_REF_LOCI_2__22'
          ],
          [
            'Human',
            '22',
            'GRC__HUMAN__ALT_REF_LOCI_3__22'
          ],
          [
            'Human',
            '22',
            'GRC__HUMAN__PLACEHOLDER__22'
          ],
          [
            'Human',
            '22',
            'UNPL_22'
          ],
          [
            'Human',
            '22',
            undef
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_1__3'
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_2__3'
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_3__3'
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_4__3'
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_5__3'
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_6__3'
          ],
          [
            'Human',
            '3',
            'GRC__HUMAN__ALT_REF_LOCI_7__3'
          ],
          [
            'Human',
            '3',
            'UNPL_3'
          ],
          [
            'Human',
            '3',
            undef
          ],
          [
            'Human',
            '4',
            'GRC__HUMAN__ALT_REF_LOCI_1__4'
          ],
          [
            'Human',
            '4',
            'GRC__HUMAN__ALT_REF_LOCI_2__4'
          ],
          [
            'Human',
            '4',
            'GRC__HUMAN__ALT_REF_LOCI_3__4'
          ],
          [
            'Human',
            '4',
            'UNPL_4'
          ],
          [
            'Human',
            '4',
            undef
          ],
          [
            'Human',
            '5',
            'GRC__HUMAN__ALT_REF_LOCI_1__5'
          ],
          [
            'Human',
            '5',
            'GRC__HUMAN__ALT_REF_LOCI_2__5'
          ],
          [
            'Human',
            '5',
            'GRC__HUMAN__PLACEHOLDER__5'
          ],
          [
            'Human',
            '5',
            'UNPL_5'
          ],
          [
            'Human',
            '5',
            undef
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_1__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_2__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_3__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_4__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_5__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_6__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_7__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__ALT_REF_LOCI_8__6'
          ],
          [
            'Human',
            '6',
            'GRC__HUMAN__PLACEHOLDER__6'
          ],
          [
            'Human',
            '6',
            undef
          ],
          [
            'Human',
            '7',
            'GRC__HUMAN__ALT_REF_LOCI_1__7'
          ],
          [
            'Human',
            '7',
            'GRC__HUMAN__ALT_REF_LOCI_2__7'
          ],
          [
            'Human',
            '7',
            'UNPL_7'
          ],
          [
            'Human',
            '7',
            undef
          ],
          [
            'Human',
            '8',
            'GRC__HUMAN__ALT_REF_LOCI_1__8'
          ],
          [
            'Human',
            '8',
            'GRC__HUMAN__ALT_REF_LOCI_2__8'
          ],
          [
            'Human',
            '8',
            'GRC__HUMAN__ALT_REF_LOCI_3__8'
          ],
          [
            'Human',
            '8',
            'GRC__HUMAN__PLACEHOLDER__8'
          ],
          [
            'Human',
            '8',
            'UNPL_8'
          ],
          [
            'Human',
            '8',
            undef
          ],
          [
            'Human',
            '9',
            'GRC__HUMAN__ALT_REF_LOCI_1__9'
          ],
          [
            'Human',
            '9',
            'UNPL_9'
          ],
          [
            'Human',
            '9',
            undef
          ],
          [
            'Human',
            'U',
            'UNPL_U'
          ],
          [
            'Human',
            'X',
            'GRC__HUMAN__ALT_REF_LOCI_1__X'
          ],
          [
            'Human',
            'X',
            'GRC__HUMAN__ALT_REF_LOCI_2__X'
          ],
          [
            'Human',
            'X',
            'GRC__HUMAN__PLACEHOLDER__X'
          ],
          [
            'Human',
            'X',
            undef
          ],
          [
            'Human',
            'Y',
            'UNPL_Y'
          ],
          [
            'Human',
            'Y',
            undef
          ],
          [
            'Mouse',
            '1',
            'GRC__MOUSE__129S6_SvEvTac__1'
          ],
          [
            'Mouse',
            '1',
            'GRC__MOUSE__129X1_SvJ__1'
          ],
          [
            'Mouse',
            '1',
            'GRC__MOUSE__NOD_MrkTac__1'
          ],
          [
            'Mouse',
            '1',
            'GRC__MOUSE__NOD_ShiLtJ__1'
          ],
          [
            'Mouse',
            '1',
            'GRC__MOUSE__UNPL__1'
          ],
          [
            'Mouse',
            '1',
            undef
          ],
          [
            'Mouse',
            '10',
            'GRC__MOUSE__MOUSE_UNKNOWN__10'
          ],
          [
            'Mouse',
            '10',
            undef
          ],
          [
            'Mouse',
            '11',
            'GRC__MOUSE__129S6_SvEvTac__11'
          ],
          [
            'Mouse',
            '11',
            'GRC__MOUSE__129X1_SvJ__11'
          ],
          [
            'Mouse',
            '11',
            'GRC__MOUSE__CAST_Ei__11'
          ],
          [
            'Mouse',
            '11',
            'GRC__MOUSE__NOD_MrkTac__11'
          ],
          [
            'Mouse',
            '11',
            'GRC__MOUSE__NOD_ShiLtJ__11'
          ],
          [
            'Mouse',
            '11',
            undef
          ],
          [
            'Mouse',
            '12',
            'GRC__MOUSE__129S1_SvImJ__12'
          ],
          [
            'Mouse',
            '12',
            'GRC__MOUSE__129S7_SvEvBrd-Hprt-b-m2__12'
          ],
          [
            'Mouse',
            '12',
            'GRC__MOUSE__BALB_c__12'
          ],
          [
            'Mouse',
            '12',
            'GRC__MOUSE__RIII__12'
          ],
          [
            'Mouse',
            '12',
            undef
          ],
          [
            'Mouse',
            '13',
            'GRC__MOUSE__129S1_SvImJ__13'
          ],
          [
            'Mouse',
            '13',
            'GRC__MOUSE__129S6_SvEvTac__13'
          ],
          [
            'Mouse',
            '13',
            'GRC__MOUSE__A_J__13'
          ],
          [
            'Mouse',
            '13',
            undef
          ],
          [
            'Mouse',
            '14',
            'GRC__MOUSE__129S1_SvImJ__14'
          ],
          [
            'Mouse',
            '14',
            'GRC__MOUSE__129X1_SvJ__14'
          ],
          [
            'Mouse',
            '14',
            undef
          ],
          [
            'Mouse',
            '15',
            'GRC__MOUSE__129S6_SvEvTac__15'
          ],
          [
            'Mouse',
            '15',
            'GRC__MOUSE__129S7_SvEvBrd-Hprt-b-m2__15'
          ],
          [
            'Mouse',
            '15',
            undef
          ],
          [
            'Mouse',
            '16',
            'GRC__MOUSE__129S1_SvImJ__16'
          ],
          [
            'Mouse',
            '16',
            'GRC__MOUSE__129S6_SvEvTac__16'
          ],
          [
            'Mouse',
            '16',
            'GRC__MOUSE__129X1_SvJ__16'
          ],
          [
            'Mouse',
            '16',
            undef
          ],
          [
            'Mouse',
            '17',
            'GRC__MOUSE__129S1_SvImJ__17'
          ],
          [
            'Mouse',
            '17',
            'GRC__MOUSE__129S6_SvEvTac__17'
          ],
          [
            'Mouse',
            '17',
            'GRC__MOUSE__129X1_SvJ__17'
          ],
          [
            'Mouse',
            '17',
            'GRC__MOUSE__MOUSE_UNKNOWN__17'
          ],
          [
            'Mouse',
            '17',
            'GRC__MOUSE__NOD_MrkTac__17'
          ],
          [
            'Mouse',
            '17',
            'GRC__MOUSE__NOD_ShiLtJ__17'
          ],
          [
            'Mouse',
            '17',
            undef
          ],
          [
            'Mouse',
            '18',
            'GRC__MOUSE__CAST_Ei__18'
          ],
          [
            'Mouse',
            '18',
            'GRC__MOUSE__RIII__18'
          ],
          [
            'Mouse',
            '18',
            undef
          ],
          [
            'Mouse',
            '19',
            'GRC__MOUSE__129P2_OlaHsd__19'
          ],
          [
            'Mouse',
            '19',
            'GRC__MOUSE__MOUSE_UNKNOWN__19'
          ],
          [
            'Mouse',
            '19',
            undef
          ],
          [
            'Mouse',
            '2',
            'GRC__MOUSE__129S1_SvImJ__2'
          ],
          [
            'Mouse',
            '2',
            undef
          ],
          [
            'Mouse',
            '3',
            'GRC__MOUSE__129S1_SvImJ__3'
          ],
          [
            'Mouse',
            '3',
            'GRC__MOUSE__NOD_MrkTac__3'
          ],
          [
            'Mouse',
            '3',
            undef
          ],
          [
            'Mouse',
            '4',
            'GRC__MOUSE__129S6_SvEvTac__4'
          ],
          [
            'Mouse',
            '4',
            'GRC__MOUSE__129S7_SvEvBrd-Hprt-b-m2__4'
          ],
          [
            'Mouse',
            '4',
            'GRC__MOUSE__129X1_SvJ__4'
          ],
          [
            'Mouse',
            '4',
            'GRC__MOUSE__MOUSE_UNKNOWN__4'
          ],
          [
            'Mouse',
            '4',
            'GRC__MOUSE__NOD_MrkTac__4'
          ],
          [
            'Mouse',
            '4',
            'GRC__MOUSE__UNPL__4'
          ],
          [
            'Mouse',
            '4',
            undef
          ],
          [
            'Mouse',
            '5',
            'GRC__MOUSE__129S1_SvImJ__5'
          ],
          [
            'Mouse',
            '5',
            'GRC__MOUSE__129S6_SvEvTac__5'
          ],
          [
            'Mouse',
            '5',
            'GRC__MOUSE__UNPL__5'
          ],
          [
            'Mouse',
            '5',
            undef
          ],
          [
            'Mouse',
            '6',
            'GRC__MOUSE__129S1_SvImJ__6'
          ],
          [
            'Mouse',
            '6',
            'GRC__MOUSE__129X1_SvJ__6'
          ],
          [
            'Mouse',
            '6',
            'GRC__MOUSE__NOD_ShiLtJ__6'
          ],
          [
            'Mouse',
            '6',
            'GRC__MOUSE__SPRET_Ei__6'
          ],
          [
            'Mouse',
            '6',
            undef
          ],
          [
            'Mouse',
            '7',
            'GRC__MOUSE__129S1_SvImJ__7'
          ],
          [
            'Mouse',
            '7',
            'GRC__MOUSE__129S2_SvPas__7'
          ],
          [
            'Mouse',
            '7',
            'GRC__MOUSE__BALB_c__7'
          ],
          [
            'Mouse',
            '7',
            'GRC__MOUSE__SPRET_Ei__7'
          ],
          [
            'Mouse',
            '7',
            'GRC__MOUSE__UNPL__7'
          ],
          [
            'Mouse',
            '7',
            undef
          ],
          [
            'Mouse',
            '8',
            'GRC__MOUSE__129S6_SvEvTac__8'
          ],
          [
            'Mouse',
            '8',
            undef
          ],
          [
            'Mouse',
            '9',
            undef
          ],
          [
            'Mouse',
            'U',
            'GRC__MOUSE__UNPL__U'
          ],
          [
            'Mouse',
            'X',
            'GRC__MOUSE__129S1_SvImJ__X'
          ],
          [
            'Mouse',
            'X',
            'GRC__MOUSE__129S6_SvEvTac__X'
          ],
          [
            'Mouse',
            'X',
            'GRC__MOUSE__UNPL__X'
          ],
          [
            'Mouse',
            'X',
            undef
          ],
          [
            'Mouse',
            'Y',
            'GRC__MOUSE__AKR_J__Y'
          ],
          [
            'Mouse',
            'Y',
            'GRC__MOUSE__CAST_Ei__Y'
          ],
          [
            'Mouse',
            'Y',
            'GRC__MOUSE__SPRET_Ei__Y'
          ],
          [
            'Mouse',
            'Y',
            'GRC__MOUSE__UNPL__Y'
          ],
          [
            'Mouse',
            'Y',
            undef
          ],
          [
            'Zebrafish',
            '1',
            undef
          ],
          [
            'Zebrafish',
            '10',
            undef
          ],
          [
            'Zebrafish',
            '11',
            undef
          ],
          [
            'Zebrafish',
            '12',
            undef
          ],
          [
            'Zebrafish',
            '13',
            undef
          ],
          [
            'Zebrafish',
            '14',
            undef
          ],
          [
            'Zebrafish',
            '15',
            undef
          ],
          [
            'Zebrafish',
            '16',
            undef
          ],
          [
            'Zebrafish',
            '17',
            undef
          ],
          [
            'Zebrafish',
            '18',
            undef
          ],
          [
            'Zebrafish',
            '19',
            undef
          ],
          [
            'Zebrafish',
            '2',
            undef
          ],
          [
            'Zebrafish',
            '20',
            undef
          ],
          [
            'Zebrafish',
            '21',
            undef
          ],
          [
            'Zebrafish',
            '22',
            undef
          ],
          [
            'Zebrafish',
            '23',
            undef
          ],
          [
            'Zebrafish',
            '24',
            undef
          ],
          [
            'Zebrafish',
            '25',
            'GRC__ZEBRAFISH__PLACEHOLDER__25'
          ],
          [
            'Zebrafish',
            '25',
            undef
          ],
          [
            'Zebrafish',
            '3',
            undef
          ],
          [
            'Zebrafish',
            '4',
            undef
          ],
          [
            'Zebrafish',
            '5',
            undef
          ],
          [
            'Zebrafish',
            '6',
            undef
          ],
          [
            'Zebrafish',
            '7',
            undef
          ],
          [
            'Zebrafish',
            '8',
            'GRC__ZEBRAFISH__PLACEHOLDER__8'
          ],
          [
            'Zebrafish',
            '8',
            undef
          ],
          [
            'Zebrafish',
            '9',
            undef
          ],
          [
            'Zebrafish',
            'U',
            undef
          ],
);

my @grc_tpf_names = get_grc_tpf_names();

print Dumper(\@grc_tpf_names) . "\n";
#is_deeply(\@grc_tpf_names, \@expected, "GRC TPF names should be as expected");
